menu:
  home: /
  archives: /archives

favicon: /favicon.ico


# Code Highlight theme
## Available value: normal | night | night eighties | night blue | night bright
## https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Fancybox
fancybox: true

# Specify the date when the site was setup
since: 2015

version: 0.1.0